[project]
name = "back-office-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Toushali Banerjee", email = "toushalibanerjee26@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.23.0",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]

[project.scripts]
back-office-classifier = "back_office_classifier:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
